<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- 被动轮宏定义 -->
    <xacro:macro name="passive_wheel" params="parent_link passive_wheel_name radius angle sphere_radius:='0.06'">
        <!-- 被动轮链接 -->
        <link name="${passive_wheel_name}">
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="0.1"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
            </inertial>
            <collision>
                <geometry>
                    <sphere radius="${float(sphere_radius)}"/>
                </geometry>
            </collision>
        </link>

        <!-- 被动轮关节 - 绕x轴旋转，在yz平面上分布，y轴负方向指向圆心 -->
        <joint name="${passive_wheel_name}_joint" type="continuous">
            <!-- 让y轴负方向指向圆心：被动轮在角度angle位置，需要绕x轴旋转angle角度使y轴负方向指向圆心 -->
            <origin xyz="0 ${float(radius) * cos(float(angle))} ${float(radius) * sin(float(angle))}" rpy="${float(angle)} 0 0"/>
            <parent link="${parent_link}"/>
            <child link="${passive_wheel_name}"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <!-- 递归宏：创建被动轮循环 -->
    <xacro:macro name="create_passive_wheels" params="parent_link wheel_name indices:=^ angle_step passive_wheel_radius_actual">
        <xacro:if value="${indices}">
            <!-- 弹出第一个索引 -->
            <xacro:property name="index" value="${indices.pop(0)}"/>
            <!-- 计算角度 -->
            <xacro:property name="angle" value="${float(index) * float(angle_step)}"/>
            <!-- 创建被动轮 -->
            <xacro:passive_wheel
                    parent_link="${parent_link}"
                    passive_wheel_name="${wheel_name}_passive_${index}"
                    radius="${passive_wheel_radius_actual}"
                    angle="${angle}"/>
            <!-- 递归调用自己 -->
            <xacro:create_passive_wheels
                    parent_link="${parent_link}"
                    wheel_name="${wheel_name}"
                    indices="${indices}"
                    angle_step="${angle_step}"
                    passive_wheel_radius_actual="${passive_wheel_radius_actual}"/>
        </xacro:if>
    </xacro:macro>

    <!-- 轮子宏定义 - 只包含轮子的link -->
    <xacro:macro name="wheel" params="wheel_name
                inertial_origin_xyz:='0.035966 2.8161E-06 7.9768E-09'
                ixx:='0.00142306' ixy:='0.00000000' ixz:='0.00000000' iyy:='0.00084449' iyz:='0.00000002' izz:='0.00084474'
                passive_wheel_radius:='0.02' wheel_radius:='0.15' num_passive_wheels:='10'
                enable_passive_wheels:='false'">
        <!-- 轮子链接 -->
        <link name="${wheel_name}">
            <inertial>
                <origin xyz="${inertial_origin_xyz}"/>
                <mass value="0.5746"/>
                <inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}" iyy="${iyy}" iyz="${iyz}" izz="${izz}"/>
            </inertial>
            <visual>
                <geometry>
                    <mesh filename="file://$(find arx_lift2s_description)/meshes/${wheel_name}.glb"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="file://$(find arx_lift2s_description)/meshes/${wheel_name}.glb"/>
                </geometry>
            </collision>
        </link>

        <!-- 根据参数决定是否创建被动轮 -->
        <xacro:if value="${enable_passive_wheels}">
            <!-- 创建10个绕一圈的被动轮 -->
            <xacro:property name="num_passive_wheels_float" value="${float(num_passive_wheels)}"/>
            <xacro:property name="angle_step" value="${2*PI / num_passive_wheels_float}"/>
            <xacro:property name="passive_wheel_radius_actual" value="0.02"/>
            <xacro:property name="indices" value="${[0,1,2,3,4,5,6,7,8,9]}"/>
            <xacro:create_passive_wheels
                    parent_link="${wheel_name}"
                    wheel_name="${wheel_name}"
                    indices="${list(indices)}"
                    angle_step="${angle_step}"
                    passive_wheel_radius_actual="${passive_wheel_radius_actual}"/>
        </xacro:if>
    </xacro:macro>
</robot>