controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7

ocs2_arm_controller:
  ros__parameters:
    update_rate: 50  # Hz
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: nero
    future_time_offset: 2.0

    home_pos: [ 0.0, -0.5, 0.0, 2.0, 0.0, 0.0, 0.0 ]